### PR TITLE
sync done

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Forgot to push those changes in the previous PR

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM if tested :)

**Comment by QuantumEnigmaa** [comment]
The helm templates inside the CRD is causing an issue

**Comment by QuantumEnigmaa** [comment]
Strange to have an issue concerning the schema when there is no schema at all in the chart

**Comment by QuantumEnigmaa** [comment]
@QuentinBisson ok to merge ?

**Comment by QuentinBisson** [comment]
If you're happy, I'm happy

**Pull request merged**
