### PR TITLE
Remove duplicate resources for the CRDs

### PR DESCRIPTION
**Pull request by primeroz**
In the current v2.0.0 version of the app each CRD is rendered twice, once from the `templates` directory and once from the `templates/crds` one

they are the same resoucces

```
➜ sha256sum *.yaml crds/*.yaml | sort -k 1
b1c8a7a327be226d8efb344bdf6d5654a977080eb059e7c8e4cea621f19f71fd  crds/verticalpodautoscalercheckpoints.yaml
b1c8a7a327be226d8efb344bdf6d5654a977080eb059e7c8e4cea621f19f71fd  verticalpodautoscalercheckpoints.yaml
c455776bb07ef1789b6b8a2dbf809783d78a3fee1a363f55cad69cf1d232aac0  crds/verticalpodautoscalers.yaml
c455776bb07ef1789b6b8a2dbf809783d78a3fee1a363f55cad69cf1d232aac0  verticalpodautoscalers.yaml
```

```
➜ helm --kubeconfig=/var/home/fciocchetti/Work/giantswarm/misc/mc-bootstrap/./kubeconfigs/fctestvpa.kubeconfig template --namespace=kube-system --values=/tmp/values.yaml --version=2.0.0 vertical-pod-autoscaler-crd control-plane-catalog/vertical-pod-autoscaler-crd | yq '.kind,.metadata.name'
CustomResourceDefinition
verticalpodautoscalercheckpoints.autoscaling.k8s.io
---
CustomResourceDefinition
verticalpodautoscalers.autoscaling.k8s.io
---
CustomResourceDefinition
verticalpodautoscalercheckpoints.autoscaling.k8s.io
---
CustomResourceDefinition
verticalpodautoscalers.autoscaling.k8s.io
```

this is breaking `mc-bootstrap`

```
--> Installing vpa-crd
---> Installing/upgrading helm "vertical-pod-autoscaler-crd" release                                                                                                                                               + helm repo add --force-update control-plane-catalog https://giantswarm.github.io/control-plane-catalog/ 
"control-plane-catalog" has been added to your repositories                                                                                                                                                        
Using konfigure to generate chart release values                                                                                                                                                                   
+ ./tools/konfigure generate --dir=./repos/config --raw --app-name vertical-pod-autoscaler-crd --installation garlic                                                                                               
+ helm_upgrade_args=("--namespace=${release_namespace}" "--values=${tmp}")                               
+ '[' x2.0.0 '!=' x ']'                                                                                                                                                                                            
+ helm_upgrade_args+=("--version=${app_version}")
+ helm --kubeconfig=/var/home/fciocchetti/Work/giantswarm/misc/mc-bootstrap/./kubeconfigs/garlic.kubeconfig upgrade --install --timeout=15m0s --namespace=kube-system --values=/tmp/giantswarm-mc-bootstrap.idPjxCF
M.vertical-pod-autoscaler-crd-values.yaml --version=2.0.0 vertical-pod-autoscaler-crd control-plane-catalog/vertical-pod-autoscaler-crd
Release "vertical-pod-autoscaler-crd" does not exist. Installing it now.                                                                                                                                           
Error: customresourcedefinitions.apiextensions.k8s.io "verticalpodautoscalercheckpoints.autoscaling.k8s.io" already exists
+ __utils_on_exit                                                                                                                                                                                                  
+ set +e                                                                                                                                                                                                           
+ popd                       
+ rm -rf /tmp/giantswarm-mc-bootstrap.idPjxCFM.vertical-pod-autoscaler-crd-values.yaml
+ set -e   
```

### CODE REVIEW

**Review by bavarianbidi — APPROVED** [review]
lgtm from `clippy` side ;-)

**Comment by primeroz** [comment]
I will wait for @giantswarm/team-atlas approval just in case i am missing something

**Comment by primeroz** [comment]
thank you, jus tto confirm even from glippy installed app the same manifests are rendered twice 

```
➜ helm get manifest -n kube-system vertical-pod-autoscaler-crd | yq -s '"file_" + $index'
```
```
 λ grep "# Source" *
file_0.yml:# Source: vertical-pod-autoscaler-crd/templates/crds/verticalpodautoscalercheckpoints.yaml
file_1.yml:# Source: vertical-pod-autoscaler-crd/templates/crds/verticalpodautoscalers.yaml
file_2.yml:# Source: vertical-pod-autoscaler-crd/templates/verticalpodautoscalercheckpoints.yaml
file_3.yml:# Source: vertical-pod-autoscaler-crd/templates/verticalpodautoscalers.yaml


 λ sed -i '/^# Source/d' *    

 λ sha256sum * | sort -k 1
521bafe0d7566be821248b259ddd9ea9d8b2f70a2e4713aa224a2c4005dc2af7  file_0.yml
521bafe0d7566be821248b259ddd9ea9d8b2f70a2e4713aa224a2c4005dc2af7  file_2.yml
54bdcc36e040f1dced70c609af8d813a85941f00c1b553d9dd1946b2cf1c1af9  file_1.yml
54bdcc36e040f1dced70c609af8d813a85941f00c1b553d9dd1946b2cf1c1af9  file_3.yml

```

**Comment by QuantumEnigmaa** [comment]
Tested on `glippy` and works fine. However, the 2 labels removed by `vpa-app` are back :/

**Comment by QuantumEnigmaa** [comment]
After redploying vpa app the labels are removed so that's great :)

**Comment by QuantumEnigmaa** [comment]
@QuentinBisson I think we can merge now right ?

**Comment by QuentinBisson** [comment]
Sure :)

**Pull request merged**
